version: "3"
services:
    mysql:
      image: mysql
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_ROOT_PASSWORD: mirth
        MYSQL_DATABASE: mirthdb
        MYSQL_USER: mirth
        MYSQL_PASSWORD: mirth        
      networks:
        - backend
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    mirth:
      depends_on:
        - mysql
      image: brandonstevens/mirth-connect
      environment:
        JDBC_URL: jdbc:mysql://mysql:3306/mirthdb?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
        JDBC_USER: mirth
        JDBC_PASS: mirth
      ports:
        - 8080:8080
        - 8443:8443
      networks:
        - frontend
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
networks:
    frontend:
    backend:
      internal: true